### ISSUE TITLE
리액트 숙련주차 개인과제 리뷰 - 김병연 튜터

### ISSUE THREAD

**Issue by ByungyeonKim** [G-NooN/fan-mail-box#6]
안녕하세요, 진훈님! 과제 제출 답변을 보니, 단계별 구현을 통해 차이점을 명확하게 이해하신 것 같네요. 💯 리액트에서는 옆 컴포넌트나 저~멀리 있는 컴포넌트에 상태를 전달하려면 상태를 끌어올리는 방법이 최선이죠. 앱이 커질수록 prop drilling은 더 깊어지고, 중간에 많은 컴포넌트를 거쳐야하기 때문에 유지보수나 디버깅도 어려워질 수 있어요. 이러한 문제를 해결하기 위해 Context를 사용하셨죠. 여기서 더 나아가 전역 상태 관리를 위한 Redux까지 사용하셨습니다. 좋네요!

> 📌 하기 리뷰는 main 브랜치를 기준으로 작성되었습니다.

## README 작성

리드미 파일 작성과 버셀에 배포까지 해주셔서, 실제 동작하는 부분들을 쉽게 확인할 수 있었습니다. 이런 부분들이 개인적으로 참 중요한 것 같아요. 리드미에서는 프로젝트에 대한 설명과 이런 것들을 구현했고, 어떤 도구들을 사용했는지도 중요하지만 본인이 느낀 경험들이나 고민들을 작성해주는 것이 좋아요. 특히 이번 과제에서는 브랜치별로 직접 구현해보면서 본인이 느낀 장단점이나 경험, 고민들이 있었을 거에요. 그런 부분들을 작성해 주시면 좋을 것 같습니다!

## 디렉토리 구조

<img width="409" alt="스크린샷 2024-02-12 오후 9 51 45" src="https://github.com/G-NooN/fan-mail-box/assets/66554164/38bf85b7-c09a-4f65-a013-4859a344006c">

제가 항상 말씀드리는 것 중에 하나가 계층적인 디렉토리 구성이 정말 중요하다고 말씀드렸었죠. 이번에는 정말 군더더기 없이 잘 구성해주셨네요. 불필요한 파일들도 모두 제거를 했고, 딱 보기에도 깔끔해서 보기에 편했습니다. 👍

## 페이지 컴포넌트

https://github.com/G-NooN/fan-mail-box/blob/9f6697461180d2a97221edb3229b5984094f7626/src/pages/Detail.jsx#L3-L9

저는 보통 페이지 컴포넌트라면 해당 페이지에 들어갈 레이아웃 컴포넌트와, 다양한 컴포넌트들의 조합이 있을거라 기대해요. 그런데 레이아웃 컴포넌트인 `MainPage.jsx`에 해당 컴포넌트들이 들어있더라구요. 이렇게 컴포넌트들을 쪼개는 것도 좋지만, 너무 잘게 쪼개지면 레이어가 깊어져 오히려 유지보수 하기가 어렵다고 생각을 해요. 레이아웃 컴포넌트들은 container나 헤더 등과 같은 큰 틀로 줄이고, 페이지 컴포넌트에 컴포넌트들을 조합하는 건 어떨까요? `Detail.jsx` 페이지 컴포넌트를 예시로 들어볼게요:

```jsx
<PageContainer>
  <SectionContainer>
    <ArtistList />
    <AddForm />
  </SectionContainer>

  <SectionContainer>
    <SectionTitle>Mail LIST</SectionTitle>
    <MailListContainer>
      {filteredMailList.length === 0 ? (
        <NoMail />
      ) : (
        filteredMailList.map((mail) => <Mail key={mail.id} mail={mail} />)
      )}
    </MailListContainer>
  </SectionContainer>
</PageContainer>
```

어떻게 생각하시나요? 이 방식이 정답은 아니기 때문에 진훈님의 의견도 궁금해요! 댓글 남겨주시면 감사하겠습니다. :)

## ActiveContext.js

`ActiveContext`는 미사용 중인 것 같아요. Redux로 옮겼다면 해당 파일은 지워도 될 것 같네요!

## 사용자 경험(UX)

곳곳에 디테일들이 많이 숨어 있네요. 사용자와 상호작용 하는 부분들이 자연스럽고, 활성/비활성화에 대한 것들도 알 수 있게 잘 구현해주셨습니다. 받는 사람 셀렉터에서 튜터/매니저로 카테고리를 나눈 것도 좋았어요. 👍

--- 

여기까지 피드백을 드려봤어요. 진훈님 코드 리뷰를 많이 해봐서 그런지 계속 성장하시는 게 보이네요! 앞으로도 응원하겠습니다. 화이팅하시고, 이번에도 고생하셨습니다. 👏

**Comment by G-NooN** [comment]
안녕하세요~ 팀 프로젝트와 기타 일정들에 치여 이제야 답변을 드리네요ㅠㅠ

## README

저도 매우 공감했던 부분입니다.  README의 의미는 알고 있었지만, 지금까지는 단순 소개, 디렉토리 구조 소개, 실행 방법 등을 설명하는 쪽으로 작성했었습니다.

이번에 튜터님의 피드백과 다른 분들의 GitHub를 참고해보고 이러한 프로젝트 형태의 repo의 README를 어떤 방식으로 작성해야 하는지 깨달았습니다.

앞으로의 프로젝트에서는 좀 더 나은 README를 완성해보도록 하겠습니다!!

## 컴포넌트 분리

사실 저도 제출하기 직전까지 고민했었습니다.
튜터님이 언급해주신대로 pages 폴더 내부의 파일들이 단순하게 하나의 레이아웃 컴포넌트만 return하기 때문에, '굳이 이렇게 한 단계 거칠 필요가 있나?' 생각했습니다.

제가 제출했을 때의 생각은 이러했습니다.
1. pages 폴더는 말 그대로 URL 분리만 진행한다 (ex. `'/'`, `'/detail/'`)
2. 각 URL 페이지의 내부 레이아웃은 layout 폴더에서 분리한다.

**폴더 구조를 어떻게 나눠야 할지, 각 폴더 이름이 구체적으로 어떤 의미인지(ex. layout, pages 등) 알고 싶습니다.**

피드백 감사합니다!!

**Comment by ByungyeonKim** [comment]
안녕하세요, 진훈님~

진훈님의 방식도 일리가 있네요. 설명해 주셔서 감사합니다! 언제나 그렇듯 정답은 없고, 본인이 생각하는 개발 철학과 이유가 있다면, 선택은 자유에요! 그치만, 언제나 모범사례는 존재하죠. 그래서 협업을 위해, 본인을 위해 더 나은 방법이 있는지 항상 고민해봐야하는 것 같습니다. 저랑 같이 고민해 보시죠! 마지막에 질문하신 것에 대한 답변을 드릴게요. 🤩

개념적으로 레이아웃은 ***경로 간에 공유되는 UI***로, 페이지는 ***경로에 고유한 UI***로 이해하면 좋을 것 같아요.

- 레이아웃: 경로 간에 공유되는 UI
- 페이지: 경로에 고유한 UI

```jsx
export function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}
```

```jsx
export function Layout({ children }) {
  return <section>{children}</section>
}
```

```jsx
export function Page() {
  return <h1>My Page</h1>
}
```

여기서 레이아웃 컴포넌트는 헤더나, 푸터, 사이드바 그리고 특정 페이지의 콘텐츠를 감싸는 wrapper 또는 container가 될 수 있습니다. 즉, 모든 페이지 또는 특정 페이지에서 반복적으로 사용되는 UI 부분들을 정의하는 거에요. 여기서 그럼 일반적인 컴포넌트 파일들과는 어떤 차이점이 있냐? 생각이 들 수 있는데요. 레이아웃 컴포넌트가 좀 더 큰틀이고, 그 안의 작은 블록 UI들이 컴포넌트라고 생각하시면 좋을 것 같아요.

- 레이아웃 컴포넌트: 특정 페이지나 앱의 전체적인 레이아웃을 구성
- 컴포넌트: 재사용 가능한 컴포넌트. 작은 UI의 단위

그렇다면, 이제 해당 컴포넌트들을 조합해놓은 컴포넌트가 페이지 컴포넌트가 아닐까..생각이 들어요!

만약, 더 자세히 알고 싶으시면 저보다 훨~씬 고민을 많이 했을 메이저 회사의 컨벤션이나 유명 유튜버의 코드를 참고하는 것도 좋아요. 나중에 배울 Nextjs는 어느 정도 규칙이 정해져 있기 때문에 좀 더 편하실 거에요.

- https://nextjs.org/docs/app/building-your-application/routing

또는 아래의 레포를 참고해 보세요. :)

- https://github.com/WebDevSimplified/react-folder-structure

그럼 진훈님, 오늘도 화이팅입니다! ✨

**Comment by G-NooN** [comment]
아하.. 지금까지 pages가 layout보다 상위 개념인 줄 알았는데, 이렇게 보니 layout이 pages보다 상위 개념이었군요.

Next.js의 규칙을 한번 참고해봐야 할 것 같습니다.

감사합니다!!
